# [START django_app]
runtime: python37

handlers:
  - url: /static
    static_dir: backend/server/static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
# [END django_app]