# Generated by Django 2.1.5 on 2019-03-11 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInVisitReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.CheckIns', verbose_name='check_in_id')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_address', models.CharField(max_length=50, null=True)),
                ('company_city', models.CharField(max_length=30, null=True)),
                ('company_zip', models.CharField(max_length=15, null=True)),
                ('company_state', models.CharField(max_length=2, null=True)),
                ('company_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('is_employee', models.BooleanField(default=False)),
                ('waiver_signed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Company', verbose_name='company_id')),
            ],
        ),
        migrations.CreateModel(
            name='VisitReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Company', verbose_name='company_id')),
            ],
        ),
        migrations.AddField(
            model_name='checkinvisitreason',
            name='visit_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.VisitReason', verbose_name='visit_reason_id'),
        ),
        migrations.AddField(
            model_name='checkins',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Visitors', verbose_name='visitor_id'),
        ),
        migrations.AlterUniqueTogether(
            name='visitors',
            unique_together={('company', 'visitor_id')},
        ),
    ]
