# Generated by Django 2.1.5 on 2019-04-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='role',
            field=models.IntegerField(default=-1),
        ),
    ]
