# Generated by Django 2.1.5 on 2019-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkins',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
