# Generated by Django 2.1.5 on 2019-04-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_invite_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invite',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
