# Generated by Django 2.1.5 on 2019-02-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190225_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_zip',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
