# Generated by Django 2.1.5 on 2019-03-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190320_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreason',
            name='has_sub_reasons',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visitreason',
            name='is_main_reason',
            field=models.BooleanField(default=False),
        ),
    ]
