# Generated by Django 2.1.5 on 2019-02-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190224_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
