# Generated by Django 2.1.5 on 2019-04-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190322_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='date_hired',
            field=models.DateTimeField(null=True),
        ),
    ]
