# Generated by Django 2.1.5 on 2019-04-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190413_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
