# Generated by Django 2.1.5 on 2019-02-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190224_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorreason',
            old_name='company_id',
            new_name='company',
        ),
    ]
