# Generated by Django 2.1.5 on 2019-02-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20190224_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkinvisitorreason',
            old_name='visitor_reason_id',
            new_name='visitor_reason',
        ),
    ]
