# Generated by Django 2.1.5 on 2019-02-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190224_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkinvisitorreason',
            old_name='CheckIn_id',
            new_name='CheckIn',
        ),
    ]
